theme: jekyll-theme-minimal
title: DCC RG
description: Digital Communities in China Research Group——We are a group of researchers who are interested in the impact of communication technologies on contemporary Chinese society.
