theme: jekyll-theme-minimal
title: Digital Communities in China Research Group (DCC RG)
description: We are a group of researchers who are interested in the impact of communication technologies on contemporary Chinese society. We are: HO Jolin Hiu-man, LEI Qinyuan, LIU Zhiyuan, TANG Ran, ZHANG Yawen, ZHOU Han
description: Our affiliated Organizations: City University of Hong Kong, University of Washington, University of Wisconsin-Madison, Fudan University
